Modify storing of status effect to make it more mod friendly
QuiltMC/quilt-standard-libraries pull request #105
Opened 2022-04-22 19:34 UTC by Patbox

Minecraft by default serializes status effects as raw registry value limited to a byte! Which isn't great mod compatibility wise (raw ids shouldn't be considered stable) and limits to supporting only 256 status effects globally!

I'm not sure if it should be part of registry package through, but it is simple to move

2022-04-22 20:17 UTC, Kroppeb approved these changes

2022-04-22 20:20 UTC, OroArmor approved these changes

2022-04-25 01:23 UTC, TheGlitch76 requested changes
A couple questions for you:
- How does this PR handle byte overflow when there are more than 256 status effects? I don't see any code to disable or otherwise affect the Vanilla method of (de)serializing effects.
- How does this PR affect situations where a modded world is moved back to vanilla? What happens?

2022-04-25 01:23 UTC, TheGlitch76 commented on library/core/registry/src/main/java/org/quiltmc/qsl/registry/mixin/patch/StatusEffectInstanceMixin.java
> +		nbt.putString("quilt:id", Registry.STATUS_EFFECT.getId(this.type).toString());
These NBT constants should be fields in an impl class somewhere.

2022-04-25 04:45 UTC, Patbox commented
> A couple questions for you:
> 
> * How does this PR handle byte overflow when there are more than 256 status effects? I don't see any code to disable or otherwise affect the Vanilla method of (de)serializing effects.
> * How does this PR affect situations where a modded world is moved back to vanilla? What happens?

For simplicity it doesn't change how vanilla stores this, as id ones have priority. MC already has null checks so it should be safe to move world back to vanilla. It will just ignore additional nbt and use byte value

2022-05-04 02:52 UTC, TheGlitch76 commented
> For simplicity it doesn't change how vanilla stores this, as id ones have priority. MC already has null checks so it should be safe to move world back to vanilla. It will just ignore additional nbt and use byte value

I don't see any code here to guard for cases where the byte value is an outright lie (like integer overflow)?

2022-05-09 15:42 UTC, OroArmor approved these changes
Just Glitch's suggestion

2022-08-11 10:13 UTC, LambdAurora approved these changes
This is necessary to ensure that status effects don't get broken on world save and provides the missing replacement for registry sync.

Now to address glitch's comments

> A couple questions for you:
>
>    How does this PR handle byte overflow when there are more than 256 status effects? I don't see any code to disable or otherwise affect the Vanilla method of (de)serializing effects.

All this code takes precedence over Vanilla, meaning if QSL is installed, QSL's way of deserialization will have priority making status effect serialization/deserialization much more reliable.

>    How does this PR affect situations where a modded world is moved back to vanilla? What happens?

If the Vanilla status effects IDs have not been jumbled, it should work just fine since the original Vanilla values are still stored as neighbors.

2022-08-11 13:43 UTC, Leo40Git approved these changes
The Flattening 2: Mojank's Leftovers
LGTM!

2022-08-11 16:31 UTC, EnnuiL approved these changes
Nitpick nitpicked, just take a look at 'em first;
Anyway, if nothing breaks on migration from raw IDs to Identifiers, then all is fine!

2022-08-11 16:31 UTC, EnnuiL commented on library/core/registry/src/main/java/org/quiltmc/qsl/registry/mixin/patch/BeaconBlockEntityMixin.java
> +	@Nullable StatusEffect secondary;
```suggestion
	@Shadow
	@Final
	private static Set<StatusEffect> EFFECTS;

	@Shadow
	@Nullable StatusEffect primary;

	@Shadow
	@Nullable StatusEffect secondary;
```

2022-08-11 16:31 UTC, EnnuiL commented on library/core/registry/src/main/java/org/quiltmc/qsl/registry/mixin/patch/SuspiciousStewItemMixin.java
> +	@SuppressWarnings({"InvalidInjectorMethodSignature"})
oh wow, it's quite a long name for a warning
although maybe the {}s aren't needed?
```suggestion
	@SuppressWarnings("InvalidInjectorMethodSignature")
```

2022-08-11 16:36 UTC, LambdAurora commented
> Anyway, if nothing breaks on migration from raw IDs to Identifiers, then all is fine!

Nothing would since if no quilt Identifier is present it automatically use the raw IDs.

2022-08-11 17:20 UTC, merged