Fixes Transitive Dependencies at compile and runtime
QuiltMC/quilt-standard-libraries pull request #107
Opened 2022-04-23 16:49 UTC by OroArmor

Read title.

2022-04-23 19:36 UTC, LambdAurora approved these changes

2022-04-23 19:36 UTC, LambdAurora commented on build-logic/src/main/java/qsl/internal/extension/QslModuleExtensionImpl.java
> +//					System.out.println(type);
Remove those comments and it'll be good to go.

2022-04-23 19:39 UTC, OroArmor commented on build-logic/src/main/java/qsl/internal/extension/QslModuleExtensionImpl.java
> +//					System.out.println();
```suggestion
```

2022-04-24 22:07 UTC, TheGlitch76 commented on build-logic/src/main/java/qsl/internal/extension/QslModuleExtensionImpl.java
> +	private void addTransitiveImplementations(QslLibraryDependency library, QslLibraryDependency.ModuleDependencyInfo info) {
this is in desperate need of some code comments explaining the motivation behind this. i only can get my bearings because we talked about it in vc

2022-04-25 11:38 UTC, Leo40Git approved these changes

2022-04-25 16:25 UTC, TheGlitch76 requested changes
meant to make previous comment changes requested, sorry!

2022-05-09 15:57 UTC, TheGlitch76 approved these changes

2022-05-09 15:58 UTC, merged