Make BiomeModifications datapack-compatible.
QuiltMC/quilt-standard-libraries pull request #139
Opened 2022-06-21 21:45 UTC by peaceheis

All this does is add a check to the vanilla dimension BiomeSelectors to check tags. Backwards compat is guaranteed, as an or has been used (I believe the Nether selector in particular needs the original check).

2022-06-21 21:47 UTC, LambdAurora reviewed
I think you have some left-overs.

2022-06-21 21:47 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
> +		TagKey<Biome> NETHER = TagKey.of(Registry.BIOME_KEY, new Identifier("minecraft", "is_nether"));
```suggestion
```

2022-06-21 21:47 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
> +		TagKey<Biome> END = TagKey.of(Registry.BIOME_KEY, new Identifier("minecraft", "is_end"));
```suggestion
```

2022-06-21 22:27 UTC, EnnuiL requested changes

2022-06-21 22:27 UTC, EnnuiL commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
> +	 * Returns a biome selector that will match all biomes that would normally spawn in the Nether. Datapack Compatible.
```suggestion
	 * Returns a biome selector that will match all biomes that would normally spawn in the Nether.
	 * This method is compatible with biomes defined on the {@code minecraft:is_nether} tag.
```
If the "Assuming Vanilla's source" line is still true, then it should be readded

2022-06-21 22:27 UTC, EnnuiL commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
> +	 * Returns a biome selector that will match all biomes that spawn in the end. Datapack compatible.
```suggestion
	 * Returns a biome selector that will match all biomes that would normally spawn in the End.
	 * This method is compatible with biomes defined on the {@code minecraft:is_end} tag.
```

2022-06-21 22:27 UTC, EnnuiL commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
>  	 * assuming Vanilla's default biome source is used.
The Javadoc for foundInOverworld hasn't been updated; It should have the same "This method is compatible with this tag" comment as the other two

2022-06-21 22:42 UTC, LambdAurora reviewed
I am gonna make checkstyle explode.

2022-06-21 22:42 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeModification.java
> +	 * <p>For modifiers that should only be applied if a given condition is met for a Biome, please add these
```suggestion
	 * <p>
	 * For modifiers that should only be applied if a given condition is met for a Biome, please add these
```

2022-06-21 22:42 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/ModificationPhase.java
> +	 * <p><b>Examples:</b> Mods that allow modpack authors to customize world generation, changing biome
```suggestion
	 * <p>
	 * <b>Examples:</b> Mods that allow modpack authors to customize world generation, changing biome
```

2022-06-21 22:42 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/ModificationPhase.java
> +	 * <p><b>Examples:</b> Replace mineshafts with biome-specific mineshafts
```suggestion
	 * <p>
	 * <b>Examples:</b> Replace mineshafts with biome-specific mineshafts
```

2022-06-21 22:42 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/ModificationPhase.java
> +	 * <p><b>Examples:</b> Remove iron ore from plains, remove ghasts
```suggestion
	 * <p>
	 * <b>Examples:</b> Remove iron ore from plains, remove ghasts
```

2022-06-21 22:42 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/ModificationPhase.java
> +	 * <p><b>Examples:</b> New ores, new vegetation, new structures
```suggestion
	 * <p>
	 * <b>Examples:</b> New ores, new vegetation, new structures
```

2022-06-21 23:34 UTC, LambdAurora approved these changes

2022-06-21 23:34 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
> +	 * This method is compatible with biomes defined on the {@code minecraft:is_overworld} tag.
```suggestion
	 * This method is compatible with biomes defined in the {@code minecraft:is_overworld} tag.
```

2022-06-21 23:34 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
> +	 * This method is compatible with biomes defined on the {@code minecraft:is_nether} tag.
```suggestion
	 * This method is compatible with biomes defined in the {@code minecraft:is_nether} tag.
```

2022-06-21 23:34 UTC, LambdAurora commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
> +	 * This method is compatible with biomes defined on the {@code minecraft:is_end} tag.
```suggestion
	 * This method is compatible with biomes defined in the {@code minecraft:is_end} tag.
```

2022-06-22 03:23 UTC, Leo40Git approved these changes

2022-06-22 09:23 UTC, oliviathevampire approved these changes

2022-06-23 23:54 UTC, OroArmor approved these changes
Fix the other suggestions and it'll be good

2022-06-25 04:03 UTC, EnnuiL requested changes

2022-06-25 04:03 UTC, EnnuiL commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
> +	 * his selector will also match modded biomes that have been added to the End using {@link TheEndBiomes}.
<p> for consistency with `foundInTheNether`, and also T

```suggestion
     * <p>
	 * This selector will also match modded biomes that have been added to the End using {@link TheEndBiomes}.
```

2022-06-25 14:32 UTC, EnnuiL requested changes

2022-06-25 14:32 UTC, EnnuiL commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/api/BiomeSelectors.java
> +     * <p>
i screwed up in the suggestion thing
```suggestion
   * <p>
```

2022-06-25 14:37 UTC, EnnuiL approved these changes
Stamped with the Ennui's ~~Making Lambda Stop Worrying About Further Delays 'Til Approval~~ Stamp of Approval

2022-06-28 21:36 UTC, merged