Better ordering of resource reloaders
QuiltMC/quilt-standard-libraries pull request #155
Opened 2022-07-25 22:03 UTC by LambdAurora

Ok, big PR.

## Better ordering API

The goal of this PR was to allow re-ordering of the resource reloaders in a more flexible manner, especially by supporting to make another reloader depend on yours.
This is useful as some people want to fire their reloaders before the Vanilla reloaders.

So to achieve this a new method has been added to `ResourceLoader` called `addPhaseOrdering(first, second)`. We also deprecate the dependecies declarations as those are unneeded and unnecessary complexity.

## Event Phase Ordering more like Public API

To achieve the new sorter a short idea came, what about just recycling the existing sorter used for event phases?
So I made that API, but in a way it can be extended for other uses (as you can see in this PR).

## Uh... care to explain what in hell happened in the resource reloaders mixins?

Uh.... during my testing I might have realized that Fabric and Quilt *might* have omitted **a lot** of injections, causing a lot of resource reloaders to be unnamed. Oops.

## Questions needing answer.

As you can see in `ResourceLoaderImpl` there's something odd, we name non `IdentifiableResourceReloaders`, I'm not a big fan of it and the question is should we log a warning for those that don't implement it?

## Conclusion

I hope y'all like it.

2022-07-26 05:41 UTC, Leo40Git approved these changes
LGTM, except for this one tiny nitpick

2022-07-26 05:41 UTC, Leo40Git commented on library/core/resource_loader/src/main/java/org/quiltmc/qsl/resource/loader/impl/ResourceLoaderImpl.java
> +		//noinspection removal
> IDEA-only warning suppression comment

hiss

2022-07-26 09:57 UTC, LambdAurora commented on library/core/resource_loader/src/main/java/org/quiltmc/qsl/resource/loader/impl/ResourceLoaderImpl.java
> +		//noinspection removal
Replaced :p

2022-07-26 18:38 UTC, EnnuiL approved these changes

2022-07-26 18:38 UTC, EnnuiL commented on library/core/resource_loader/src/main/java/org/quiltmc/qsl/resource/loader/impl/ResourceReloaderPhaseData.java
> +		public void markBefore() {}
I was gonna say "`{ }`"!!!" But actually, I prefer `{}`, it's just that one annoying Checkstyle rule

2022-07-28 12:57 UTC, oliviathevampire approved these changes

2022-07-28 13:20 UTC, Leo40Git approved these changes
These annotations activate my neurons

LGTM!

2022-07-28 16:48 UTC, PepperCode1 approved these changes

2022-07-29 12:30 UTC, ExoPlant approved these changes
LGTM!

2022-07-29 12:58 UTC, Leo40Git requested changes
OOPS WAIT almost missed these javadocs!

2022-07-29 12:58 UTC, Leo40Git commented on library/core/resource_loader/src/main/java/org/quiltmc/qsl/resource/loader/api/reloader/ResourceReloaderKeys.java
> +	 * Represents the before Vanilla resource reloaders application phase.
```suggestion
	 * Represents the application phase before Vanilla resource reloaders are invoked.
```

2022-07-29 12:58 UTC, Leo40Git commented on library/core/resource_loader/src/main/java/org/quiltmc/qsl/resource/loader/api/reloader/ResourceReloaderKeys.java
> +	 * Represents the after Vanilla resource reloaders application phase.
```suggestion
	 * Represents the application phase after Vanilla resource reloaders are invoked.
```

2022-07-29 13:01 UTC, Leo40Git approved these changes
Okay, _now_ it LGTM!

2022-08-04 16:22 UTC, merged