Item Interaction Events
QuiltMC/quilt-standard-libraries pull request #182
Opened 2022-08-22 15:54 UTC by Leo40Git

As the name implies, this adds events that fire when using items.

This PR adds the `item_extensions` module.

### TODO
- [x] "Used on block" event
- [ ] "Used on entity" event

2022-08-22 18:34 UTC, OroArmor requested changes
Looks good, but i think it would fit better under an `item_event` module

2022-08-23 10:06 UTC, Leo40Git commented
Moved to `item_events`!

2022-08-24 08:20 UTC, 0xJoeMama commented
Hm it all looks good, but what is your opinion on a adding generic UseItem event as well? One that fires when the 'use' method is called?
Maybe an 'inventoryTick' event as well, although that's not really an interaction and is therefore not in line with this PR's description.

My point is, this can be expanded. We should look into that.

2022-09-27 10:05 UTC, Leo40Git commented on library/item/item_events/src/main/java/org/quiltmc/qsl/item/events/api/ItemInteractionEvents.java
> +		throw new UnsupportedOperationException("BlockInteractionEvents only contains static declarations.");
```suggestion
		throw new UnsupportedOperationException("ItemInteractionEvents only contains static declarations.");
```

2023-07-19 03:50 UTC, closed without merging