Rename registry_entry_attachments to registry_entry_attachment
QuiltMC/quilt-standard-libraries pull request #190
Opened 2022-09-04 13:06 UTC by Leo40Git

The old ID will still work, as a "provides" entry has been added.

This PR also touches the `block_content_registry` and `item_content_registry` modules (hence Core reviews being requested). And by that, I mean that there is a one character change in their `build.gradle` file.

2022-09-04 13:09 UTC, LambdAurora approved these changes

2022-09-04 16:16 UTC, OroArmor approved these changes

2022-09-04 16:19 UTC, EnnuiL approved these changes

2022-09-04 17:21 UTC, EnnuiL requested changes
Wait! The testmod has to be renamed too

2022-09-10 17:28 UTC, EnnuiL approved these changes

2022-09-12 19:00 UTC, merged