More flexible ItemGroup addition API
QuiltMC/quilt-standard-libraries pull request #199
Opened 2022-10-08 19:01 UTC by lukebemish

This relatively small API adds a single method to register ItemGroups not created through the QuiltItemGroup builder.

2022-10-08 19:03 UTC, OroArmor approved these changes
@LambdAurora @EnnuiL Should we make a standard for import order so that prs dont change them every time?

2022-10-08 19:04 UTC, EnnuiL commented
> @LambdAurora @EnnuiL Should we make a standard for import order so that prs dont change them every time?

That's called Checkstyle, and people should always use it

2022-10-08 19:14 UTC, lukebemish commented
> > @LambdAurora @EnnuiL Should we make a standard for import order so that prs dont change them every time?
> 
> That's called Checkstyle, and people should always use it

Might want to add something to https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19/CONTRIBUTING.md about it then - it doesn't appear to be autodetected by my IDE or anything

2022-10-08 19:18 UTC, EnnuiL commented
> > > @LambdAurora @EnnuiL Should we make a standard for import order so that prs dont change them every time?
> > 
> > 
> > That's called Checkstyle, and people should always use it
> 
> Might want to add something to https://github.com/QuiltMC/quilt-standard-libraries/blob/1.19/CONTRIBUTING.md about it then - it doesn't appear to be autodetected by my IDE or anything

That's a fair point; We really need to document that

2022-10-08 19:19 UTC, LambdAurora commented
You need the checkstyle Intellij plugin (if you're using Intellij, otherwise, good luck)
then import it as a code style
if you only import the file in the plugin settings it won't modify the auto-formatter

2022-10-08 19:20 UTC, lukebemish commented
> You need the checkstyle Intellij plugin (if you're using Intellij, otherwise, good luck) then import it as a code style if you only import the file in the plugin settings it won't modify the auto-formatter

Sounds good. I can set that up to make sure it is styled right here. Once again, though, I'd add this to the CONTRIBUTING.md - it's not at all obvious to someone that hasn't made a PR here before

2022-10-08 19:26 UTC, lukebemish commented
Huh. My IDE likes to insert the imports as I try to move them around to get them in the right order for checkstyle; checkstyle is also entirely uninformative besides "they're not ordered right". Lovely. I'll get that fixed shortly.

2022-10-09 14:50 UTC, lukebemish commented
Alright, fixed the format stuff.

2022-10-09 23:14 UTC, EnnuiL approved these changes

2022-10-10 21:31 UTC, EnnuiL requested changes
A microscopic nitpick:

2022-10-10 21:31 UTC, EnnuiL commented on library/item/item_group/src/testmod/java/org/quiltmc/qsl/item/group/test/ItemGroupTest.java
> +	private static final ItemGroup NOT_QUILT_ITEM_GROUP = QuiltItemGroup.register(index -> new ItemGroup(index, NAMESPACE+".test_not_quilt_group") {
```suggestion
	private static final ItemGroup NOT_QUILT_ITEM_GROUP = QuiltItemGroup.register(index -> new ItemGroup(index, NAMESPACE + ".test_not_quilt_group") {
```

2022-10-11 00:22 UTC, EnnuiL approved these changes

2022-10-19 00:48 UTC, merged