Change Multipart Entity API's "rotate" methods to work as intended
QuiltMC/quilt-standard-libraries pull request #222
Opened 2022-11-26 14:32 UTC by Arathain

This PR changes the rotate() methods of AbstractMultipartEntity to rotate the vectors via pitch and yaw only, which also fixes the bug where pitch and yaw rotations would not stack (as result of using quaternions, presumably).
It addionally adds the option to switch between degrees and radians without having to use *(float)Math.PI/180f every time.

2022-11-26 20:15 UTC, EnnuiL requested changes
I'll make an exception to my break to point something: Could you readd the removing methods for 1.19.2? Breaking compatibility might not be a great idea despite it being the kind of fundamental change that is needed *but* 1.19.3 is coming soon; I'll want to fast-track this PR so I can already remove the deprecated functions before 1.19.3 releases

2022-11-27 15:02 UTC, Arathain commented
Like so?

2022-11-27 15:08 UTC, EnnuiL requested changes
Minor nitpickS, but yep! Like that! But don't worry, we'll quickly get rid of those on 1.19.3

2022-11-27 15:08 UTC, EnnuiL commented on library/entity/multipart/src/main/java/org/quiltmc/qsl/entity/multipart/api/AbstractEntityPart.java
> +	/**
```suggestion
	}

	/**
```

2022-11-27 15:08 UTC, EnnuiL commented on library/entity/multipart/src/main/java/org/quiltmc/qsl/entity/multipart/api/AbstractEntityPart.java
> +	/**
```suggestion
	}

	/**
```

2022-11-27 15:10 UTC, Arathain commented
alright, done

2022-11-27 15:15 UTC, EnnuiL approved these changes

2022-12-01 23:23 UTC, LambdAurora approved these changes

2022-12-02 16:30 UTC, williambl requested changes
Just one nitpick.

2022-12-02 16:30 UTC, williambl commented on library/entity/multipart/src/main/java/org/quiltmc/qsl/entity/multipart/api/AbstractEntityPart.java
>  	 * @param yaw   the rotation about y-axis in degrees
Javadoc is inaccurate.

```suggestion
	 * @param pitch   the rotation about x-axis
	 * @param yaw     the rotation about y-axis
	 * @param degrees whether the rotation should be done in degrees or radians
```

2022-12-04 04:03 UTC, merged