Update to 1.19.4-rc2
QuiltMC/quilt-standard-libraries pull request #284
Opened 2023-03-10 02:22 UTC by TheGlitch76

The QM intermediary distribution now uses Intermediary instead of Hashed for methods and fields (which makes sense, and solves a lot of problems). However, this means a lot of changing needs done.

I've gotten a good portion done; anyone who has a green checkmark is able to push to this branch and help out.

2023-03-10 02:26 UTC, OroArmor approved these changes

2023-03-10 02:28 UTC, EnnuiL requested changes
Looks good and I like the usage of `@Slice`s here! Just few nitpicks (with all of them having a GH suggestion)

2023-03-10 02:28 UTC, EnnuiL commented on build-logic/src/main/java/qsl/internal/Versions.java
> +	public static final List<MinecraftVersion> COMPATIBLE_VERSIONS = versions(MINECRAFT_VERSION.getFancyString());
...?

2023-03-10 02:28 UTC, EnnuiL commented on library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/mixin/OxidizableMixin.java
> +
```suggestion
```

2023-03-10 02:28 UTC, EnnuiL commented on library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/mixin/OxidizableMixin.java
> +	// replaces old map with one updated by registry attachments
```suggestion
	// Lambda in assignment of OXIDATION_LEVEL_INCREASES
	// Replaces old map with one updated by registry attachments
```

2023-03-10 02:28 UTC, EnnuiL commented on library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/mixin/OxidizableMixin.java
> +	// Replace old map with one updated by our api
```suggestion
	// Replaces old map with one updated by our API
```

2023-03-10 02:28 UTC, EnnuiL commented on library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/mixin/HoneycombItemMixin.java
> +	// Replace old map with one updated by our api
```suggestion
	// Replaces old map with one updated by our API
```

2023-03-10 02:28 UTC, EnnuiL commented on library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/mixin/HoneycombItemMixin.java
> +	// Replace old map with one updated by our api
```suggestion
	// Replaces old map with one updated by our API
```

2023-03-10 02:28 UTC, EnnuiL commented on library/item/item_setting/src/main/java/org/quiltmc/qsl/item/setting/mixin/recipe_remainder/C_pzubrkmcMixin.java
> +	// normal unmapped method
Hm, I guess this comment isn't really necessary...?
```suggestion
```

2023-03-10 02:28 UTC, EnnuiL commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/mixin/TheEndBiomeSourceMixin.java
> +		CODEC = RecordCodecBuilder.create((instance) -> instance.group(RegistryOps.retrieveGetter(RegistryKeys.BIOME)).apply(instance, instance.stable(TheEndBiomeSource::method_46680)));
I think the {} was intentional as a way of shortening the line length? I won't ask for changes here though

2023-03-10 02:28 UTC, EnnuiL commented on library/worldgen/dimension/src/testmod/java/org/quiltmc/qsl/worldgen/dimension/EmptyChunkGenerator.java
> +
```suggestion
	public void method_40450(List<String> list, RandomState randomState, BlockPos pos) {}
```

2023-03-10 22:18 UTC, EnnuiL commented on library/block/block_content_registry/src/main/java/org/quiltmc/qsl/block/content/registry/mixin/OxidizableMixin.java
> +
```suggestion
```

2023-03-11 00:21 UTC, EnnuiL commented on library/worldgen/biome/src/main/java/org/quiltmc/qsl/worldgen/biome/mixin/TheEndBiomeSourceMixin.java
> +		CODEC = RecordCodecBuilder.create((instance) -> instance.group(RegistryOps.retrieveGetter(RegistryKeys.BIOME)).apply(instance, instance.stable(TheEndBiomeSource::method_46680)));
...because I'd rather do the changes myself :P

2023-03-11 00:31 UTC, EnnuiL approved these changes

2023-03-11 00:31 UTC, merged