Fix: Modify Tag path behavior in Dynamic Registries
QuiltMC/quilt-standard-libraries pull request #329
Opened 2023-07-23 21:41 UTC by cocona20xx

Causes all modded Dynamic Registries to use `tags/NAMESPACE/path/to/file` for tag paths instead of `tags/path/to/file`, where `NAMESPACE` is the namespace of the Dynamic Registry. 

This prevents accidental namespace collision in tags, and could be considered a bugfix as it was intended behavior in the Dynamic Registry API to begin with.

2023-07-23 21:44 UTC, cocona20xx commented on library/data/tags/src/main/resources/quilt_tags.mixins.json
This is probably an artifact of an earlier implementation of the fix, can be 'removed' in a commit if desired to keep the number of changes lower, though it doesn't actually change any functionality.

2023-07-24 09:55 UTC, Pyrofab commented on library/data/tags/src/main/resources/quilt_tags.mixins.json
Well I do think it's cleaner to have the mixins in order so no reason to revert it I'd say ?

2023-07-24 09:57 UTC, LambdAurora commented
Could a tag be added for testing in the testmod?

2023-07-25 01:12 UTC, cocona20xx commented
> Could a tag be added for testing in the testmod?

Done as of 3293df2

2023-07-29 04:04 UTC, EnnuiL requested changes
Other than style nitpicks (and uh, maybe a heckton of them :p), the only thing blocking this PR is really a missing license header; Otherwise, this PR can be merged and fast-tracked

2023-07-29 04:04 UTC, EnnuiL commented on library/core/registry/src/main/java/org/quiltmc/qsl/registry/mixin/TagManagerLoaderMixin.java
> +		Identifier id = registry.getValue();
The review is pretty much going to be a tale of `var`s and newlines :p
```suggestion
		var id = registry.getValue();

```

2023-07-29 04:04 UTC, EnnuiL commented on library/core/registry/src/main/java/org/quiltmc/qsl/registry/mixin/TagManagerLoaderMixin.java
> +package org.quiltmc.qsl.registry.mixin;
wait oh no, we have a missing license here;
Don't forget to run `./gradlew applyLicenses`! (dw, it's safe this time around)

2023-07-29 04:04 UTC, EnnuiL commented on library/core/registry/src/testmod/java/org/quiltmc/qsl/registry/test/dynamic/RegistryLibDynamicRegistryTest.java
> +	private static final Identifier GREETING_TEST_TAG_ID = new Identifier("quilt_registry_testmod", "test_tag");
Oh, from what I saw in the code, you could directly create the TagKey here, having a `GREETING_TEST_TAG` object instead

2023-07-29 04:04 UTC, EnnuiL commented on library/core/registry/src/testmod/java/org/quiltmc/qsl/registry/test/dynamic/RegistryLibDynamicRegistryTest.java
> +		Set<TagValues<Greetings>> tagValuesSet = TagRegistry.stream(Greetings.REGISTRY_KEY).collect(Collectors.toSet());
```suggestion
		var tagKey = TagKey.of(Greetings.REGISTRY_KEY, GREETING_TEST_TAG_ID);
		var tagValuesSet = TagRegistry.stream(Greetings.REGISTRY_KEY).collect(Collectors.toSet());

```

2023-07-29 04:04 UTC, EnnuiL commented on library/core/registry/src/testmod/java/org/quiltmc/qsl/registry/test/dynamic/RegistryLibDynamicRegistryTest.java
> +			Registry<Greetings> greetingsRegistry = ctx.getWorld().getRegistryManager().get(Greetings.REGISTRY_KEY);
Yes, the original code had one of those too, I would change the other instance if I was me :p
```suggestion
			var greetingsRegistry = ctx.getWorld().getRegistryManager().get(Greetings.REGISTRY_KEY);
```

2023-07-29 04:04 UTC, EnnuiL commented on library/core/registry/src/testmod/java/org/quiltmc/qsl/registry/test/dynamic/RegistryLibDynamicRegistryTest.java
> +			Greetings testerA = greetingsRegistry.getOrEmpty(GREETING_A_ID).orElse(null);
```suggestion
			var testerA = greetingsRegistry.getOrEmpty(GREETING_A_ID).orElse(null);
```
although hm, thinking about it, maybe this bit could be simplified a bit? i'll tinker with the code once it's merged

2023-07-29 04:04 UTC, EnnuiL commented on library/core/registry/src/testmod/java/org/quiltmc/qsl/registry/test/dynamic/RegistryLibDynamicRegistryTest.java
> +			return tagValues.key().equals(tagKey) && heldIds.contains(testerA);
```suggestion
			var heldIds = new HashSet<>();
			tagValues.values().iterator().forEachRemaining(greetingsHolder -> heldIds.add(greetingsHolder.value()));

			return tagValues.key().equals(tagKey) && heldIds.contains(testerA);
```

2023-07-29 23:35 UTC, EnnuiL approved these changes
While I still have style nitpicks, I'll unblock this PR now that it compiles :p

2023-07-31 05:24 UTC, LemmaEOF approved these changes

2023-07-31 14:40 UTC, EnnuiL approved these changes
don't invalidate my reviews ;-;

2023-07-31 20:40 UTC, merged