PR Policy
QuiltMC/quilt-standard-libraries pull request #39
Opened 2021-10-07 17:14 UTC by TheGlitch76

Uses RFC 39 to define how PRs are accepted into QSL.

Some notes of how this affects the QSL team:
### Powers of the QSL team

- Approve urgent PRs (exclusive)
- Add and remove members of subteams (exclusive)
- Request changes in PRs to block them from being merged until the issues are addressed
- Merge accepted PRs that have left the final comment period (exclusive)
- Join as many or as few subteams as they'd like

The QSL team cannot just merge whatever they want; they must go through this process (with the exception of trivial fixes)

We will have a bot eventually that will manage the final comment period stuff

2021-10-07 19:42 UTC, Leo40Git approved these changes

2021-10-07 20:18 UTC, sylv256 commented on CONTRIBUTING.md
> +To get a pull request merged into QSL, it must get a certain number of approvals from the maintainers of each library the pull request targets, and then it will enter a Final Comment Period. If the p
Who are the "maintainers" of each library?

2021-10-07 20:19 UTC, sylv256 commented on CONTRIBUTING.md
> +To get a pull request merged into QSL, it must get a certain number of approvals from the maintainers of each library the pull request targets, and then it will enter a Final Comment Period. If the p
Oh, did you make the RFC yet? :confused:

2021-10-07 20:20 UTC, sylv256 commented on CONTRIBUTING.md
> +To get a pull request merged into QSL, it must get a certain number of approvals from the maintainers of each library the pull request targets, and then it will enter a Final Comment Period. If the p
Nevermind. The link you provided 404s because it doesn't link to a PR.

2021-10-09 23:49 UTC, i509VCB approved these changes

2021-10-09 23:49 UTC, i509VCB commented on CONTRIBUTING.md
> +For pull requests that must be merged quickly, like ports of critical core modules or game-breaking bug fixes.
Probably a good idea to add anything related to publishing and distributing of qsl in buildscripts.

2021-10-14 00:09 UTC, OroArmor approved these changes

2021-11-11 22:37 UTC, LemmaEOF approved these changes
LGTM/LGTM

2021-12-23 21:36 UTC, TheGlitch76 commented
Hello,
I've updated the PR policy to reflect that the current QSL team does not have all of its subteam positions full. With the new version, an approval from a member of the QSL Core team overrides the requirement for an approval by a specific subteam. I recommend reconsidering this after QSL's release, when the QSL team is (hopefully) much larger.

2021-12-23 21:44 UTC, LambdAurora requested changes
Please target the 1.18 branch.

> With the new version, an approval from a member of the QSL Core team overrides the requirement for an approval by a specific subteam. I recommend reconsidering this after QSL's release, when the QSL team is (hopefully) much larger.

I would formulate this in a much more general manner, what about formulating it in a way that doesn't require further modification, like: if the affected team has one member or less, then a core team member can provide the missing requirements.

2021-12-23 21:49 UTC, TheGlitch76 commented
> if the affected team has one member or less, then a core team member can provide the missing requirements.

I like this idea, only one issue: what do we do in cases where a team officially has two or more members, but they are no longer active contributors?

2021-12-23 23:27 UTC, OroArmor approved these changes

2022-02-07 20:19 UTC, LambdAurora commented
> I like this idea, only one issue: what do we do in cases where a team officially has two or more members, but they are no longer active contributors? This isn't something I considered when I originally wrote this policy; it just struck me.

If after 7 days of non-response, or if the contributor gives permission, QSL core members could override?

2022-02-18 20:53 UTC, TheGlitch76 commented
I added a clause that the QSL core team may waive the requirement for a subteam review if the team is inactive. QSL Core isn't a zero-trust team, so I think it will work fine.
This whole process is just a guideline and basically unenforceable in a strict sense anyway

2022-02-18 21:59 UTC, TheGlitch76 commented on CONTRIBUTING.md
> +
```suggestion
```

2022-02-18 22:04 UTC, TheGlitch76 commented
I added a proper guide to the PR policy, explaining the steps to getting a PR merged and how triage categories etc. work

2022-02-18 22:17 UTC, LambdAurora approved these changes

2022-02-18 22:18 UTC, TheGlitch76 commented
The FCP for this policy will end in 7 days, assuming no major concerns are raised.

2022-02-18 22:28 UTC, P03W approved these changes

2022-02-25 23:54 UTC, merged