Game Rule API
QuiltMC/quilt-standard-libraries pull request #55
Opened 2021-11-27 21:59 UTC by ByMartrixx

Port of Fabric's Game Rule API

2021-11-27 23:05 UTC, EnnuiL requested changes
Uuh, from my own experiences on making Boring Default Game Rules and Damage Incorporated, Fabric's Game Rule API has room for improvement
The order of the game rule categories are scrambled even if they are all registered by one mod, the name text of enum rules has an inadequate width for wrapping, and compared to Vanilla's game rule types, the Fabric ones are unnecessarily restrictive on the access of its internals (in fact, I ended needing to create Accessors, and all of them were on Fabric API's rules)
I think a revamp of the module similar to the Quilt Tags API one would be more appropriate instead of a direct port, but here's my suggestions of what could be done now:

2021-11-27 23:05 UTC, EnnuiL commented on library/content_other/game_rule/src/main/java/org/quiltmc/qsl/game_rule/impl/rule/BoundedIntRule.java
> +	private final int maximumValue;
Both minimum and maximum values need getters; The reason for that is that it may be useful for a mod that needs to directly access a game rule's bound (example: Boring Default Game Rules and its generation of a JSON Schema based on the game rules)

2021-11-27 23:05 UTC, EnnuiL commented on library/content_other/game_rule/src/main/java/org/quiltmc/qsl/game_rule/api/rule/DoubleRule.java
> +	private final double maximumValue;
Same here

2021-11-27 23:09 UTC, EnnuiL requested changes
oh whoops, forgot this one

2021-11-27 23:09 UTC, EnnuiL commented on library/content_other/game_rule/src/main/java/org/quiltmc/qsl/game_rule/api/rule/EnumRule.java
> +	private final List<E> supportedValues;
I think supportedValues also needs a getter too

2021-11-27 23:15 UTC, EnnuiL requested changes
Oh, and finally, DoubleRule needs a `void set(boolean, MinecraftServer)` method; The vanilla ones have it, why not DoubleRule?

2021-12-03 02:43 UTC, i509VCB commented
As the primary author of the game rules api from fabric API, I grant QuiltMC license to the code under the Apache 2.0 license.

For the sake of not causing more license issues, I wouldn't worry about the headers in the impl and mixin packages or the testmod source set.

2022-01-16 21:11 UTC, EnnuiL requested changes
The lack of a `void set(double, MinecraftServer)` method for DoubleRule still needs to be addressed, otherwise, it's fine for now

2022-01-16 21:21 UTC, TheGlitch76 commented
My only concern here is that now that i'm actually staring at it a lot, `content_other` is a really awkward name for a library. I think it should have been `other_content` in the first place.

cc @LambdAurora

2022-01-16 21:38 UTC, williambl commented on library/content_other/game_rule/src/main/java/org/quiltmc/qsl/game_rule/api/CustomGameRuleCategory.java
> +public final class CustomGameRuleCategory {
Could this be a record?

2022-08-22 22:18 UTC, TheGlitch76 commented
Hi--this PR seems to be unmaintained right now. I'm converting it to a draft to signify that it's not in a mergable state.

Feel free to mark it as ready for review once you begin working on this again.

2022-08-23 01:16 UTC, EnnuiL commented
About a Game Rules API, I believe that a direct port of Fabric's one will not be adequate here. With that (and also the inactivity), I'm closing this PR

2022-08-23 01:16 UTC, closed without merging